# Generated by Django 5.0.4 on 2024-04-13 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brief', models.TextField(default='Add the required text brief')),
                ('Role', models.CharField(choices=[('ui/ux', 'ui/ux'), ('frontend', 'frontend'), ('backend', 'backend'), ('product-manager', 'product-manager')], max_length=200)),
                ('Industry', models.CharField(choices=[('Technology', 'techology'), ('Fashion', 'fashion'), ('Food & Beverages', 'food & beverages'), ('Health & wellness', 'health & wellness'), ('Entertainment', 'entertainment'), ('Travel & hospitality', 'travel & hospitality')], max_length=200)),
                ('Difficulty', models.CharField(choices=[('Easy', 'easy'), ('Intermidiate', 'intermidiate'), ('Hard', 'hard')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taskgenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('ui/ux', 'ui/ux'), ('frontend', 'frontend'), ('backend', 'backend'), ('product-manager', 'product-manager')], max_length=200)),
                ('Industry', models.CharField(choices=[('Technology', 'techology'), ('Fashion', 'fashion'), ('Food & Beverages', 'food & beverages'), ('Health & wellness', 'health & wellness'), ('Entertainment', 'entertainment'), ('Travel & hospitality', 'travel & hospitality')], max_length=200)),
                ('Difficulty', models.CharField(choices=[('Easy', 'easy'), ('Intermidiate', 'intermidiate'), ('Hard', 'hard')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
