# Generated by Django 5.0.4 on 2024-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgenerator',
            name='Brief',
            field=models.TextField(default='add a brief', editable=False),
        ),
    ]
