# Generated by Django 5.0.4 on 2024-04-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskgenerator', '0002_taskgenerator_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskgenerator',
            name='user',
        ),
    ]
