# Generated by Django 5.0.4 on 2024-04-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgenerator', '0003_remove_admin_user_remove_taskgenerator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Duration',
            field=models.CharField(choices=[('1 day', '1 day'), ('1 week', '1 week'), ('1 month', '1 month')], default='pick the duration you want to work on', max_length=200),
        ),
        migrations.AddField(
            model_name='taskgenerator',
            name='Duration',
            field=models.CharField(choices=[('1 day', '1 day'), ('1 week', '1 week'), ('1 month', '1 month')], default='pick the duration you want to work on', max_length=200),
        ),
    ]
